---
title: "Data Cleaning"
author: "Andrew.Z.Flores"
date: "`r Sys.Date()`"
output: html_document
---
```{r warning=FALSE, include=FALSE}
# Load required libraries
library(tidyverse) # Required for data manipulation
library(here)      # Required for creating portable file paths
library(data.table)
```

```{r , load data, include=FALSE, include=FALSE}
mcdi_data <- fread(here("data", "MCDI_06_10_23.csv"))
mcdi_data <- mcdi_data %>% select(data_id,value,age,item_definition,item_kind)
# Rename columns in the excluded_mcdi dataframe
column_names <- c("subject",
                  "produce",
                  "age",
                  "word",
                  "type"
      )

mcdi_data <- mcdi_data %>% setNames(column_names)

#add lexical class to each word
col_names2 <- c("word","lexical_class")
item_info <- fread(here("data", "raw_mcdi.csv")) %>% 
  select(definition,lexical_class) %>% unique() %>% 
  setNames(col_names2)

mcdi_data <- mcdi_data %>% left_join(item_info)
```

# Identify the unique levels of subjects
```{r, unique_subjects}
# Identify the unique levels of subjects
unique_subjects <- mcdi_data %>% 
  pull(subject) %>% 
  unique() %>% 
  sort()
```


# MCDI 
## Data Exclusion
In the current data set we exclude items if they fit any of the following 
criteria: \newline

1. Belonging to the "other" category.
2. Have categorical responses (e.g., "often", "sometimes").
3. Form compound words (e.g., play dough, butterfly).
4. Can act as noun or verb (e.g., can (object), can (auxiliary)).
5. Specific Items
```{r, exclude_mcdi}

# Create a vector of items to exclude based on lexical class
other_items <- mcdi_data %>%
  filter(lexical_class == "other") %>%
  pull(word) %>% unique()

# Create a vector of items to exclude based on type
other_types <- mcdi_data %>%
  filter(type != "word") %>%
  pull(type) %>% unique()

# replaces specific word meaning (e.g "drink (beverage)" with lemma (drink))
mcdi_data$word <-
  recode(
    mcdi_data$word,
    "buttocks/bottom*" = "bottom",
    "call (on phone)" = "call",
    "can (object)" = "can",
    "chicken (animal)" = "chicken",
    "church*" = "church",
    "clean (action)" = "clean",
    "daddy*" = "daddy",
    "did/did ya" = "did",
    "drink (beverage)" = "drink",
    "dress (object)" = "dress",
    "dry (action)" = "dry",
    "fish (animal)" = "fish",
    "gonna/going to" = "gonna",
    "gotta/got to" = "gotta",
    "grandma*" = "grandma",
    "grandpa*" = "grandpa",
    "hafta/have to" = "hafta",
    "inside/in" = "inside",
    "lemme/let me" = "lemme",
    "little (description)" = "little",
    "mommy*" = "mommy",
    "need/need to" = "need",
    "orange (food)" = "orange",
    "owie/boo boo" = "owie",
    "soda/pop" = "soda",
    "slide (object)" = "slide",
    "swing (object)" = "swing",
    "tissue/kleenex" = "tissue",
    "toy (object)" = "toy",
    "try/try to" = "try",
    "wanna/want to" = "wanna",
    "water (beverage)" = "water",
    "watch (object)" = "watch",
    "work (place)" = "work"
  )




mcdi_data$word <-
  recode(
    mcdi_data$word,
    # Convert to singular
    "grrr"  = "grr",
    "beads" = "bead",
    "beans" = "bean",
    "boots" = "boot",
    "bubbles" = "bubble",
    "camping" = "camp",
    "carrots" = "carrot",
    "cheerios" = "cheerio",
    "daddy" = "dad",
    "gloves" = "glove",
    "grapes" = "grape",
    "keys" = "key",
    "lips" = "lip",
    "mittens" = "mitten",
    "mommy" = "mom",
    "noisy" = "noise",
    "noodles" = "noodle",
    "nuts" = "nut",
    "owie" = "ow",
    "peas" ="pea",
    "scared" = "scare",
    "vitamins" = "vitamin",
    "yucky" = "yuck")


# remove words from analysis
excluded_items <-
  c(
    # open form compound words
    "baa baa", 
    "choo choo", 
    "quack quack", 
    "uh oh", 
    "woof woof", 
    "yum yum",
    "play dough", 
    "french fries", 
    "green beans",
    "ice cream", 
    "peanut butter", 
    "potato chip", 
    "belly button", 
    "high chair",
    "living room", 
    "rocking chair", 
    "washing machine", 
    "play pen", 
    "lawn mower",
    "gas station", 
    "babysitter's name", 
    "child's own name", 
    "pet's name",
    "give me five!", 
    "gonna get you!", 
    "go potty", 
    "night night", 
    "so big!",
    "thank you", 
    "this little piggy", 
    "turn around", 
    "all gone", 
    "next to", 
    "on top of",
    "a lot",
    
    # remove homographs
    "drink (action)",
    "slide (action)", 
    "swing (action)", 
    "watch (action)", 
    "work (action)",
    "clean (description)", 
    "dry (description)", 
    "orange (description)",
    "can (auxiliary)", 
    "water (not beverage)", 
    "chicken (food)", 
    "fish (food)", 
    
    # closed-compound words
    "butterfly", 
    "airplane", 
    "firetruck", 
    "motorcycle", 
    "applesauce", 
    "hamburger", 
    "lollipop", 
    "popcorn", 
    "strawberry", 
    "snowsuit",
    "underpants", 
    "toothbrush", 
    "bathroom", 
    "bathtub", 
    "backyard",
    "babysitter",
    "sandbox",
    "sidewalk", 
    "snowman", 
    "yourself", 
    "bedroom",
    "cowboy",
    "dirty",
    "downtown",
    "fireman", 
    "glasses", 
    "grandma", 
    "grandpa",
    "hafta",
    "mailman",
    "necklace",
    "outside",
    "pancake",
    "pattycake",
    "playground",
    "teddybear",
    
    
    #word endings
    "hers", 
    "jeans",
    "jelly",
    "kitty",
    "pajamas",
    "pants",
    "penny",
    "don't",
    "potty",
    "puppy",
    "scissors",
    "shopping",
    "shorts",
    "sleepy",
    "stairs",
    "sticky",
    "tights",
    "tired",
    "windy",
    "woods",
    "cookie",
    "does",
   
    # belong to "other" lexical class
    "dad",
    "mom",
    "call",
    "camp",
    "grr",
    "mom",
    "work",
    "church",
    
    
    #specific items
    "peekaboo",
    "TV",
    "I",
    "penis*", 
    "vagina*",
    "lemme"
    )


# Filter rows with a word in other_items or a type in other_types
filtered_mcdi <- mcdi_data %>%
  filter(!(word %in% other_items | type %in% other_types))

# Remove excluded words from the dataframe
excluded_mcdi <- filtered_mcdi %>% filter(!word %in% excluded_items)

# Calculate MCDIp values
mcdip_df <- excluded_mcdi %>% 
  mutate(produce = if_else(produce == "produces", 1, 0)) %>% 
  group_by(word, age) %>% 
  summarize(MCDIp = mean(produce, na.rm = TRUE))

# Merge the MCDIp values with the excluded_mcdi dataframe
excluded_mcdi <- excluded_mcdi %>% 
  mutate(produce = if_else(produce == "produces", 1, 0))
excluded_mcdi <- full_join(excluded_mcdi, mcdip_df)

```

```{r, select_columns}

# Order excluded_mcdi by word and age
excluded_mcdi <- excluded_mcdi %>% arrange(word, age)

# Extract unique target words
unique_target_words <- excluded_mcdi %>% select(word,lexical_class) %>% unique()

# Extract unique MCDIp values for each word at each age
unique_mcdip <- excluded_mcdi %>% select(age, word, MCDIp) %>% unique()
```

```{r, save_files}
write.csv(excluded_mcdi, file = here("data", "preprocessed_mcdi.csv"), row.names = FALSE)
write.csv(unique_mcdip, file = here("data","MCDIp_unique.csv"), row.names = FALSE)
write.csv(unique_target_words, file = here("data","target_words.csv"), row.names = FALSE)
```


























































































































