---
title: "Data Cleaning"
author: "Andrew.Z.Flores"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
# Load required packages
library(tidyverse)
library(data.table)
library(here)   
```

```{r}
preprocessed_mcdi <- fread(here("data", "preprocessed_mcdi.csv"))
distributional_statistics <- fread(here("data", "distributional_statistics.csv"))

```

```{r}
full_dataset <- full_join(preprocessed_mcdi,distributional_statistics)
```

```{r, create regression data}
# create new variables
regression_dataset <- full_dataset %>% 
  mutate(log_FQ = log10(FQ+1)) %>% 
  mutate(FQ_scaled = scale(log_FQ)) %>% 
  mutate(LD_scaled = scale(LD)) %>% 
  mutate(DD_scaled = scale(DD)) %>% 
  mutate(PKC_scaled = scale(PKC))

regression_dataset <- regression_dataset %>% 
  select(subject,produce,age,word,
         MCDIp,FQ_scaled,LD_scaled,
         DD_scaled,PKC_scaled)
```

```{r, create descriptive data}
plotting_dataset <- full_dataset %>% 
  mutate(log_FQ = log10(FQ+1)) %>%
  select(age,word,lexical_class,
         MCDIp,log_FQ,LD,
         DD,PKC) %>% unique()
```

```{r, save_datasets}
write.csv(regression_dataset, file = here("data","regression_dataset.csv"),row.names = F)
write.csv(plotting_dataset, file = here("data","plotting_dataset.csv"), row.names = F)

```












