---
title: '|6.1|Infetential Statistics Graphs'
output: pdf_document
---

```{r}
library(tidyverse)
#library(MASS)
library(lme4)
library(tibble)
library(janitor)
library(gt)
```


# Single Predictor Models
## 18 Months
```{r, add model parameters to single table}
# Frequency
model8.0_beta<- as.data.frame(model8.0_summary$coefficients)
model8.0_ci<- as.data.frame(confint.merMod(model8.0, method = "Wald"))
model8.0_beta <- rownames_to_column(model8.0_beta)
model8.0_ci <- rownames_to_column(model8.0_ci)


model8.0_R2 <- model8.0_performance[[1]]
model8.0_R2 <- model8.0_R2 %>% mutate(model = "model8.0")

model8.0 <- full_join(model8.0_beta,model8.0_ci) 
model8.0 <- model8.0 %>% mutate(model = "model8.0")
model8.0 <- full_join(model8.0,model8.0_R2)
model8.0 <- model8.0 %>% filter(rowname != ".sig01")
model8.0 <- model8.0 %>% filter(rowname != ".sig02")

# Lexical Diversity
model8.1_beta<- as.data.frame(model8.1_summary$coefficients)
model8.1_ci<- as.data.frame(confint.merMod(model8.1, method = "Wald"))
model8.1_beta <- rownames_to_column(model8.1_beta)
model8.1_ci <- rownames_to_column(model8.1_ci)


model8.1_R2 <- model8.1_performance[[1]]
model8.1_R2 <- model8.1_R2 %>% mutate(model = "model8.1")

model8.1 <- full_join(model8.1_beta,model8.1_ci) 
model8.1 <- model8.1 %>% mutate(model = "model8.1")
model8.1 <- full_join(model8.1,model8.1_R2)
model8.1 <- model8.1 %>% filter(rowname != ".sig01")
model8.1 <- model8.1 %>% filter(rowname != ".sig02")

# Document Diversity

model8.2_beta<- as.data.frame(model8.2_summary$coefficients)
model8.2_ci<- as.data.frame(confint.merMod(model8.2, method = "Wald"))
model8.2_beta <- rownames_to_column(model8.2_beta)
model8.2_ci <- rownames_to_column(model8.2_ci)


model8.2_R2 <- model8.2_performance[[1]]
model8.2_R2 <- model8.2_R2 %>% mutate(model = "model8.2")

model8.2 <- full_join(model8.2_beta,model8.2_ci) 
model8.2 <- model8.2 %>% mutate(model = "model8.2")
model8.2 <- full_join(model8.2,model8.2_R2)
model8.2 <- model8.2 %>% filter(rowname != ".sig01")
model8.2 <- model8.2 %>% filter(rowname != ".sig02")

# Pro-KWo

model8.3_beta<- as.data.frame(model8.3_summary$coefficients)
model8.3_ci<- as.data.frame(confint.merMod(model8.3, method = "Wald"))
model8.3_beta <- rownames_to_column(model8.3_beta)
model8.3_ci <- rownames_to_column(model8.3_ci)


model8.3_R2 <- model8.3_performance[[1]]
model8.3_R2 <- model8.3_R2 %>% mutate(model = "model8.3")

model8.3 <- full_join(model8.3_beta,model8.3_ci) 
model8.3 <- model8.3 %>% mutate(model = "model8.3")
model8.3 <- full_join(model8.3,model8.3_R2)
model8.3 <- model8.3 %>% filter(rowname != ".sig01")
model8.3 <- model8.3 %>% filter(rowname != ".sig02")

# join single model 18 month data

singleModels_18 <- full_join(model8.0,model8.1) %>% full_join(model8.2) %>% 
  full_join(model8.3)
singleModels_18 <- singleModels_18 %>% mutate(Age = 18)
```

## 21 Months
```{r, add model parameters to single table}
# Frequency
model9.0_beta<- as.data.frame(model9.0_summary$coefficients)
model9.0_ci<- as.data.frame(confint.merMod(model9.0, method = "Wald"))
model9.0_beta <- rownames_to_column(model9.0_beta)
model9.0_ci <- rownames_to_column(model9.0_ci)


model9.0_R2 <- model9.0_performance[[1]]
model9.0_R2 <- model9.0_R2 %>% mutate(model = "model9.0")

model9.0 <- full_join(model9.0_beta,model9.0_ci) 
model9.0 <- model9.0 %>% mutate(model = "model9.0")
model9.0 <- full_join(model9.0,model9.0_R2)
model9.0 <- model9.0 %>% filter(rowname != ".sig01")
model9.0 <- model9.0 %>% filter(rowname != ".sig02")

# Lexical Diversity
model9.1_beta<- as.data.frame(model9.1_summary$coefficients)
model9.1_ci<- as.data.frame(confint.merMod(model9.1, method = "Wald"))
model9.1_beta <- rownames_to_column(model9.1_beta)
model9.1_ci <- rownames_to_column(model9.1_ci)


model9.1_R2 <- model9.1_performance[[1]]
model9.1_R2 <- model9.1_R2 %>% mutate(model = "model9.1")

model9.1 <- full_join(model9.1_beta,model9.1_ci) 
model9.1 <- model9.1 %>% mutate(model = "model9.1")
model9.1 <- full_join(model9.1,model9.1_R2)
model9.1 <- model9.1 %>% filter(rowname != ".sig01")
model9.1 <- model9.1 %>% filter(rowname != ".sig02")

# Document Diversity

model9.2_beta<- as.data.frame(model9.2_summary$coefficients)
model9.2_ci<- as.data.frame(confint.merMod(model9.2, method = "Wald"))
model9.2_beta <- rownames_to_column(model9.2_beta)
model9.2_ci <- rownames_to_column(model9.2_ci)


model9.2_R2 <- model9.2_performance[[1]]
model9.2_R2 <- model9.2_R2 %>% mutate(model = "model9.2")

model9.2 <- full_join(model9.2_beta,model9.2_ci) 
model9.2 <- model9.2 %>% mutate(model = "model9.2")
model9.2 <- full_join(model9.2,model9.2_R2)
model9.2 <- model9.2 %>% filter(rowname != ".sig01")
model9.2 <- model9.2 %>% filter(rowname != ".sig02")

# Pro-KWo

model9.3_beta<- as.data.frame(model9.3_summary$coefficients)
model9.3_ci<- as.data.frame(confint.merMod(model9.3, method = "Wald"))
model9.3_beta <- rownames_to_column(model9.3_beta)
model9.3_ci <- rownames_to_column(model9.3_ci)


model9.3_R2 <- model9.3_performance[[1]]
model9.3_R2 <- model9.3_R2 %>% mutate(model = "model9.3")

model9.3 <- full_join(model9.3_beta,model9.3_ci) 
model9.3 <- model9.3 %>% mutate(model = "model9.3")
model9.3 <- full_join(model9.3,model9.3_R2)
model9.3 <- model9.3 %>% filter(rowname != ".sig01")
model9.3 <- model9.3 %>% filter(rowname != ".sig02")

# join single model 21 month data

singleModels_21 <- full_join(model9.0,model9.1) %>% full_join(model9.2) %>% 
  full_join(model9.3)
singleModels_21 <- singleModels_21 %>% mutate(Age = 21)
```

## 24 Months
```{r, add model parameters to single table}
# Frequency
model10.0_beta<- as.data.frame(model10.0_summary$coefficients)
model10.0_ci<- as.data.frame(confint.merMod(model10.0, method = "Wald"))
model10.0_beta <- rownames_to_column(model10.0_beta)
model10.0_ci <- rownames_to_column(model10.0_ci)


model10.0_R2 <- model10.0_performance[[1]]
model10.0_R2 <- model10.0_R2 %>% mutate(model = "model10.0")

model10.0 <- full_join(model10.0_beta,model10.0_ci) 
model10.0 <- model10.0 %>% mutate(model = "model10.0")
model10.0 <- full_join(model10.0,model10.0_R2)
model10.0 <- model10.0 %>% filter(rowname != ".sig01")
model10.0 <- model10.0 %>% filter(rowname != ".sig02")

# Lexical Diversity
model10.1_beta<- as.data.frame(model10.1_summary$coefficients)
model10.1_ci<- as.data.frame(confint.merMod(model10.1, method = "Wald"))
model10.1_beta <- rownames_to_column(model10.1_beta)
model10.1_ci <- rownames_to_column(model10.1_ci)


model10.1_R2 <- model10.1_performance[[1]]
model10.1_R2 <- model10.1_R2 %>% mutate(model = "model10.1")

model10.1 <- full_join(model10.1_beta,model10.1_ci) 
model10.1 <- model10.1 %>% mutate(model = "model10.1")
model10.1 <- full_join(model10.1,model10.1_R2)
model10.1 <- model10.1 %>% filter(rowname != ".sig01")
model10.1 <- model10.1 %>% filter(rowname != ".sig02")

# Document Diversity

model10.2_beta<- as.data.frame(model10.2_summary$coefficients)
model10.2_ci<- as.data.frame(confint.merMod(model10.2, method = "Wald"))
model10.2_beta <- rownames_to_column(model10.2_beta)
model10.2_ci <- rownames_to_column(model10.2_ci)


model10.2_R2 <- model10.2_performance[[1]]
model10.2_R2 <- model10.2_R2 %>% mutate(model = "model10.2")

model10.2 <- full_join(model10.2_beta,model10.2_ci) 
model10.2 <- model10.2 %>% mutate(model = "model10.2")
model10.2 <- full_join(model10.2,model10.2_R2)
model10.2 <- model10.2 %>% filter(rowname != ".sig01")
model10.2 <- model10.2 %>% filter(rowname != ".sig02")

# Pro-KWo

model10.3_beta<- as.data.frame(model10.3_summary$coefficients)
model10.3_ci<- as.data.frame(confint.merMod(model10.3, method = "Wald"))
model10.3_beta <- rownames_to_column(model10.3_beta)
model10.3_ci <- rownames_to_column(model10.3_ci)


model10.3_R2 <- model10.3_performance[[1]]
model10.3_R2 <- model10.3_R2 %>% mutate(model = "model10.3")

model10.3 <- full_join(model10.3_beta,model10.3_ci) 
model10.3 <- model10.3 %>% mutate(model = "model10.3")
model10.3 <- full_join(model10.3,model10.3_R2)
model10.3 <- model10.3 %>% filter(rowname != ".sig01")
model10.3 <- model10.3 %>% filter(rowname != ".sig02")

# join single model 24 month data

singleModels_24 <- full_join(model10.0,model10.1) %>% full_join(model10.2) %>% 
  full_join(model10.3)
singleModels_24 <- singleModels_24 %>% mutate(Age = 24)
```

## 27 Months
```{r, add model parameters to single table}
# Frequency
model11.0_beta<- as.data.frame(model11.0_summary$coefficients)
model11.0_ci<- as.data.frame(confint.merMod(model11.0, method = "Wald"))
model11.0_beta <- rownames_to_column(model11.0_beta)
model11.0_ci <- rownames_to_column(model11.0_ci)


model11.0_R2 <- model11.0_performance[[1]]
model11.0_R2 <- model11.0_R2 %>% mutate(model = "model11.0")

model11.0 <- full_join(model11.0_beta,model11.0_ci) 
model11.0 <- model11.0 %>% mutate(model = "model11.0")
model11.0 <- full_join(model11.0,model11.0_R2)
model11.0 <- model11.0 %>% filter(rowname != ".sig01")
model11.0 <- model11.0 %>% filter(rowname != ".sig02")

# Lexical Diversity
model11.1_beta<- as.data.frame(model11.1_summary$coefficients)
model11.1_ci<- as.data.frame(confint.merMod(model11.1, method = "Wald"))
model11.1_beta <- rownames_to_column(model11.1_beta)
model11.1_ci <- rownames_to_column(model11.1_ci)


model11.1_R2 <- model11.1_performance[[1]]
model11.1_R2 <- model11.1_R2 %>% mutate(model = "model11.1")

model11.1 <- full_join(model11.1_beta,model11.1_ci) 
model11.1 <- model11.1 %>% mutate(model = "model11.1")
model11.1 <- full_join(model11.1,model11.1_R2)
model11.1 <- model11.1 %>% filter(rowname != ".sig01")
model11.1 <- model11.1 %>% filter(rowname != ".sig02")

# Document Diversity

model11.2_beta<- as.data.frame(model11.2_summary$coefficients)
model11.2_ci<- as.data.frame(confint.merMod(model11.2, method = "Wald"))
model11.2_beta <- rownames_to_column(model11.2_beta)
model11.2_ci <- rownames_to_column(model11.2_ci)


model11.2_R2 <- model11.2_performance[[1]]
model11.2_R2 <- model11.2_R2 %>% mutate(model = "model11.2")

model11.2 <- full_join(model11.2_beta,model11.2_ci) 
model11.2 <- model11.2 %>% mutate(model = "model11.2")
model11.2 <- full_join(model11.2,model11.2_R2)
model11.2 <- model11.2 %>% filter(rowname != ".sig01")
model11.2 <- model11.2 %>% filter(rowname != ".sig02")

# Pro-KWo

model11.3_beta<- as.data.frame(model11.3_summary$coefficients)
model11.3_ci<- as.data.frame(confint.merMod(model11.3, method = "Wald"))
model11.3_beta <- rownames_to_column(model11.3_beta)
model11.3_ci <- rownames_to_column(model11.3_ci)


model11.3_R2 <- model11.3_performance[[1]]
model11.3_R2 <- model11.3_R2 %>% mutate(model = "model11.3")

model11.3 <- full_join(model11.3_beta,model11.3_ci) 
model11.3 <- model11.3 %>% mutate(model = "model11.3")
model11.3 <- full_join(model11.3,model11.3_R2)
model11.3 <- model11.3 %>% filter(rowname != ".sig01")
model11.3 <- model11.3 %>% filter(rowname != ".sig02")

# join single model 27 month data

singleModels_27 <- full_join(model11.0,model11.1) %>% full_join(model11.2) %>% 
  full_join(model11.3)
singleModels_27 <- singleModels_27 %>% mutate(Age = 27)
```

## 30 Months
```{r, add model parameters to single table}
# Frequency
model12.0_beta<- as.data.frame(model12.0_summary$coefficients)
model12.0_ci<- as.data.frame(confint.merMod(model12.0, method = "Wald"))
model12.0_beta <- rownames_to_column(model12.0_beta)
model12.0_ci <- rownames_to_column(model12.0_ci)


model12.0_R2 <- model12.0_performance[[1]]
model12.0_R2 <- model12.0_R2 %>% mutate(model = "model12.0")

model12.0 <- full_join(model12.0_beta,model12.0_ci) 
model12.0 <- model12.0 %>% mutate(model = "model12.0")
model12.0 <- full_join(model12.0,model12.0_R2)
model12.0 <- model12.0 %>% filter(rowname != ".sig01")
model12.0 <- model12.0 %>% filter(rowname != ".sig02")

# Lexical Diversity
model12.1_beta<- as.data.frame(model12.1_summary$coefficients)
model12.1_ci<- as.data.frame(confint.merMod(model12.1, method = "Wald"))
model12.1_beta <- rownames_to_column(model12.1_beta)
model12.1_ci <- rownames_to_column(model12.1_ci)


model12.1_R2 <- model12.1_performance[[1]]
model12.1_R2 <- model12.1_R2 %>% mutate(model = "model12.1")

model12.1 <- full_join(model12.1_beta,model12.1_ci) 
model12.1 <- model12.1 %>% mutate(model = "model12.1")
model12.1 <- full_join(model12.1,model12.1_R2)
model12.1 <- model12.1 %>% filter(rowname != ".sig01")
model12.1 <- model12.1 %>% filter(rowname != ".sig02")

# Document Diversity

model12.2_beta<- as.data.frame(model12.2_summary$coefficients)
model12.2_ci<- as.data.frame(confint.merMod(model12.2, method = "Wald"))
model12.2_beta <- rownames_to_column(model12.2_beta)
model12.2_ci <- rownames_to_column(model12.2_ci)


model12.2_R2 <- model12.2_performance[[1]]
model12.2_R2 <- model12.2_R2 %>% mutate(model = "model12.2")

model12.2 <- full_join(model12.2_beta,model12.2_ci) 
model12.2 <- model12.2 %>% mutate(model = "model12.2")
model12.2 <- full_join(model12.2,model12.2_R2)
model12.2 <- model12.2 %>% filter(rowname != ".sig01")
model12.2 <- model12.2 %>% filter(rowname != ".sig02")

# Pro-KWo

model12.3_beta<- as.data.frame(model12.3_summary$coefficients)
model12.3_ci<- as.data.frame(confint.merMod(model12.3, method = "Wald"))
model12.3_beta <- rownames_to_column(model12.3_beta)
model12.3_ci <- rownames_to_column(model12.3_ci)


model12.3_R2 <- model12.3_performance[[1]]
model12.3_R2 <- model12.3_R2 %>% mutate(model = "model12.3")

model12.3 <- full_join(model12.3_beta,model12.3_ci) 
model12.3 <- model12.3 %>% mutate(model = "model12.3")
model12.3 <- full_join(model12.3,model12.3_R2)
model12.3 <- model12.3 %>% filter(rowname != ".sig01")
model12.3 <- model12.3 %>% filter(rowname != ".sig02")

# join single model 30 month data

singleModels_30 <- full_join(model12.0,model12.1) %>% full_join(model12.2) %>% 
  full_join(model12.3)
singleModels_30 <- singleModels_30 %>% mutate(Age = 30)
```

```{r, join all single models}

singleModels_allAges  <- full_join(singleModels_18,singleModels_21) %>% 
  full_join(singleModels_24) %>% full_join(singleModels_27) %>% full_join(singleModels_30)

                                   
singleModels_allAges_s <- singleModels_allAges %>% select(Age,rowname,Estimate,`Std. Error`,`z value`,`Pr(>|z|)`,`2.5 %`,`97.5 %`)      

singleModels_allAges_s_2 <- singleModels_allAges_s %>% filter (rowname != "(Intercept)")

#round numbers to 2 sig digits
singleModels_allAges_s_3 <- singleModels_allAges_s_2 %>% mutate(across(is.numeric, ~ round(., 3)))

singleModels_allAges_s_3$rowname <- as.character(singleModels_allAges_s_3$rowname)

singleModels_allAges_s_3$rowname[singleModels_allAges_s_3$rowname == "s_original_freq"] <- "Frequency"
singleModels_allAges_s_3$rowname[singleModels_allAges_s_3$rowname == "s_original_ld"] <- "Lexical Diversity" 
singleModels_allAges_s_3$rowname[singleModels_allAges_s_3$rowname == "s_original_dd"] <- "Document Diversity" 
singleModels_allAges_s_3$rowname[singleModels_allAges_s_3$rowname == "s_original_pkc"] <- "Pro-KWo" 

singleModels_allAges_s_3$rowname <- as.factor(singleModels_allAges_s_3$rowname)
```

# |7|Table3. Single Predictor Model Summary and Performance
```{r}

single_models_data <- as_tibble(singleModels_allAges_s_3)
single_modelTable<- single_models_data %>% gt(rowname_col = "row", groupname_col = "rowname") %>%
  tab_options(table.font.size = 30, table.align = "left") %>% 
  #tab_spanner(label = "Model Estimates", columns = matches("Estimate|Std. Error|z value|Pr(>|z|)|2.5 %|97.5 %")) %>%
   #tab_spanner(label = "Overall Model Fit", columns = matches("AIC|BIC|R2_conditional|R2_marginal|ICC|RMSE")) %>%
tab_header(
  title = md("Mixed Effects Models with Single Predictors"),
  subtitle = md(" Production ~ *Predictor* + (1|Subject) + (1|Word)")
)  %>%
  tab_source_note(md("All data analysis code found at: *https://github.com/AzFlores/Pro-KWo*")) %>% 
  gtsave(
    "|7|Table3. Single_Predictor_Table.png", expand = 10
  )

```
# Full Model

## 18 Months
```{r, add model parameters to single table}
# 18
model13_beta<- as.data.frame(model13_summary$coefficients)
model13_ci<- as.data.frame(confint.merMod(model13, method = "Wald"))
model13_beta <- rownames_to_column(model13_beta)
model13_ci <- rownames_to_column(model13_ci)


model13_R2 <- model13_performance[[1]]
model13_R2 <- model13_R2 %>% mutate(model = "model13")

model13 <- full_join(model13_beta,model13_ci) 
model13 <- model13 %>% mutate(model = "model13")
model13 <- full_join(model13,model13_R2)
model13 <- model13 %>% filter(rowname != ".sig01")
model13 <- model13 %>% filter(rowname != ".sig02")

model13 <- model13 %>% mutate(Age = 18)
#21
model14_beta<- as.data.frame(model14_summary$coefficients)
model14_ci<- as.data.frame(confint.merMod(model14, method = "Wald"))
model14_beta <- rownames_to_column(model14_beta)
model14_ci <- rownames_to_column(model14_ci)


model14_R2 <- model14_performance[[1]]
model14_R2 <- model14_R2 %>% mutate(model = "model14")

model14 <- full_join(model14_beta,model14_ci) 
model14 <- model14 %>% mutate(model = "model14")
model14 <- full_join(model14,model14_R2)
model14 <- model14 %>% filter(rowname != ".sig01")
model14 <- model14 %>% filter(rowname != ".sig02")

model14 <- model14 %>% mutate(Age = 21)
# 24
model15_beta<- as.data.frame(model15_summary$coefficients)
model15_ci<- as.data.frame(confint.merMod(model15, method = "Wald"))
model15_beta <- rownames_to_column(model15_beta)
model15_ci <- rownames_to_column(model15_ci)


model15_R2 <- model15_performance[[1]]
model15_R2 <- model15_R2 %>% mutate(model = "model15")

model15 <- full_join(model15_beta,model15_ci) 
model15 <- model15 %>% mutate(model = "model15")
model15 <- full_join(model15,model15_R2)
model15 <- model15 %>% filter(rowname != ".sig01")
model15 <- model15 %>% filter(rowname != ".sig02")

model15 <- model15 %>% mutate(Age = 24)

# 27
model16_beta<- as.data.frame(model16_summary$coefficients)
model16_ci<- as.data.frame(confint.merMod(model16, method = "Wald"))
model16_beta <- rownames_to_column(model16_beta)
model16_ci <- rownames_to_column(model16_ci)


model16_R2 <- model16_performance[[1]]
model16_R2 <- model16_R2 %>% mutate(model = "model16")

model16 <- full_join(model16_beta,model16_ci) 
model16 <- model16 %>% mutate(model = "model16")
model16 <- full_join(model16,model16_R2)
model16 <- model16 %>% filter(rowname != ".sig01")
model16 <- model16 %>% filter(rowname != ".sig02")

model16 <- model16 %>% mutate(Age = 27)
# 30
model17_beta<- as.data.frame(model17_summary$coefficients)
model17_ci<- as.data.frame(confint.merMod(model17, method = "Wald"))
model17_beta <- rownames_to_column(model17_beta)
model17_ci <- rownames_to_column(model17_ci)


model17_R2 <- model17_performance[[1]]
model17_R2 <- model17_R2 %>% mutate(model = "model17")

model17 <- full_join(model17_beta,model17_ci) 
model17 <- model17 %>% mutate(model = "model17")
model17 <- full_join(model17,model17_R2)
model17 <- model17 %>% filter(rowname != ".sig01")
model17 <- model17 %>% filter(rowname != ".sig02")

model17 <- model17 %>% mutate(Age = 30)
# join single model 18 month data

Full_models <- full_join(model13,model14) %>% full_join(model15) %>% 
  full_join(model16) %>% full_join(model17)

```

```{r, }

Full_models <- Full_models %>% select(Age,rowname,Estimate,`Std. Error`,`z value`,`Pr(>|z|)`,`2.5 %`,`97.5 %`)    

Full_models <- Full_models %>% filter (rowname != "(Intercept)")

#round numbers to 2 sig digits
Full_models <- Full_models %>% mutate(across(is.numeric, ~ round(., 3)))

Full_models$rowname <- as.character(Full_models$rowname)

Full_models$rowname[Full_models$rowname == "s_original_freq"] <- "Frequency"
Full_models$rowname[Full_models$rowname == "s_original_ld"] <- "Lexical Diversity" 
Full_models$rowname[Full_models$rowname == "s_original_dd"] <- "Document Diversity" 
Full_models$rowname[Full_models$rowname == "s_original_pkc"] <- "Pro-KWo" 

Full_models$rowname <- as.factor(Full_models$rowname)
```

# Table 4. All Predictor Model Summary and Performance
```{r}
Full_model_data <- as_tibble(Full_models)
all_modelTable<- Full_model_data %>% gt(rowname_col = "row", groupname_col = "Age") %>%
  tab_options(table.font.size = 30, table.align = "left") %>% 
  #tab_spanner(label = "Model Estimates", columns = matches("Estimate|Std. Error|z value|Pr(>|z|)|2.5 %|97.5 %")) %>%
   #tab_spanner(label = "Overall Model Fit", columns = matches("AIC|BIC|R2_conditional|R2_marginal|ICC|RMSE")) %>%
tab_header(
  title = md("Mixed Effects Models with All Predictors"),
  subtitle = md(" Production ~ Frequency +  Lexical Diversity + Document Diversity + Pro-KWo + (1|Subject) + (1|Word)")
)  %>%
  tab_source_note(md("All data analysis code found at: *https://github.com/AzFlores/Pro-KWo*")) %>% 
  gtsave(
    "|7|Table4. All_Predictor_Table.png", expand = 10
  )
```

# Figure5. 3 Single Predictor Models

```{r}
single_models_data$Age <- as.factor(single_models_data$Age)
figure5_data <- ggplot(data=single_models_data, 
                       aes(x = Age,
                           y = Estimate, 
                           group = rowname)) 

figure5_data <- figure5_data + geom_pointrange(ymin = single_models_data$`2.5 %` ,ymax= single_models_data$`97.5 %`, size = 1)

  
figure5_data <- figure5_data + geom_line(aes(color = rowname), size = 2) + geom_point(aes(color = rowname), size = 2)

figure5_data <- figure5_data + scale_color_manual(values = c("#eeb1a2","#02a699","#f45c51","#274dc6"), labels = c("Frequency", "Lexical Diversity", "Document Diversity", "Pro-KWo"))

figure5_data <- figure5_data + labs( x = "Age (mo)" , y = "Estimate Value")     

figure5_data <- figure5_data + theme_bw() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank() ,
        plot.title = element_text(hjust = 0.5),
        panel.spacing.x = unit(1.5,"lines"),
        strip.background = element_rect(fill = "#00539CFF" ) ,
        strip.text = element_text(colour = "#FFD662FF" ) ,
        panel.border = element_rect(color = "steelblue", size = 1, fill = NA), 
        text = element_text(size=28, face = "bold", hjust = 0.5), 
        axis.text.x = element_text(size = 17, face = "bold"),
        axis.text.y = element_text(size = 20, face = "bold")) 

figure5_data <- figure5_data + theme(text = element_text(size=25, hjust = 0.5), legend.position = "top", legend.title = element_blank())


ggsave(figure5_data, filename = "|7|Figure 3.Single Model Estimates.jpeg", width = 12, height = 13)

```
